name: CleanParser Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checking Out Code
      uses: actions/checkout@v3
    - name: Install .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.10
        include-prerelease: false
    - name: Restoring Nuget Packages
      run: dotnet restore
    - name: Building Project
      run: dotnet build --no-restore
    - name: Running Tests
      run: dotnet test --no-build --verbosity normal
